### ISSUE TITLE
Seems to be missing package.json with 'express' dependency. 

### ISSUE THREAD

**Issue by nathaniel-miller** [learn-co-curriculum/angular-using-scope-apply-lab#7]
Couldn't get the specs to run. Got `Error: Error: Cannot find module 'express'`.

Creating the following package solved the issue.
``{
    "name": "angular",
    "version": "1.0.0",
    "devDependencies": {
     "express": "^4.13.4"
    }
 }

**Comment by pickledyamsman** [comment]
@aturkewi There are 5 open issues that all same the same thing here and I ran into it again tonight. Express is the reason it isn't working with an error message of

`/ ♥ learn
[21:45:23] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[21:45:23] I/launcher - Running 1 instances of WebDriver
[21:45:24] E/launcher - Error: Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Kris/Development/code/angular-using-scope-apply-lab-v-000/spec/server.js:1:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[21:45:24] E/launcher - Process exited with error code 100
You appear to be missing npm dependencies. Try running &#96;npm install&#96;
If the issue persists, check the package.json`

running npm express install was all I did to resolve but this package would work better!

**Comment by gj** [comment]
Fixed in https://github.com/learn-co-curriculum/angular-using-scope-apply-lab/commit/76ee56999cc437141af698eba93d2bcfd22fa9a7.

Sorry about that @nathaniel-miller !
